### ISSUE TITLE
Error Game doesnt found

### ISSUE THREAD

**Issue by Bladen123** [Slluxx/IconGrabber#1]
Hello there i think ur App is outdated since we tryed 3 different API keys and revoked them and created new and still doesnt work.
2 weeks before worked fine now it doesnt i dont know why but i think its steamgriddb side a change to api or so may u check that out ?

Thank you

**Comment by Slluxx** [comment]
I just tested it and it works fine. Are you sure you put in the right API key?

**Comment by Bladen123** [comment]
Hello Slluxx ur indeed right , that the app works perfectly without any issues. Yes API was right , i just find out that my Nintendo Switch Clock Time wasnt properly set on present time - i used the Tesla Overlay ( QuickNTP.ovl ) and set the time right based on Europe Time pool . and since than it runs flawlessly thank you so much.
and sorry for the false alarm . Thank you Have a nice day
