### ISSUE TITLE
Handle DMCA hidden images properly

### ISSUE THREAD

**Issue by Schaefers** [Slluxx/IconGrabber#2]
Following Nintendos takedowns (https://arstechnica.com/gaming/2022/11/nintendo-goes-after-fan-made-custom-steam-icons-with-dmca-takedowns) the homebrew crashes as soon as any of the images in the search results are taken down.

I checked steamgriddb's API there seems to be a boolean indicating that the image is hidden (even though it's not documented), e.g. this entry:

```json
        {
            "author": {
                "avatar": "https://avatars.akamai.steamstatic.com/a83a2292db538f8c2f4218ddaf828900e185a226_medium.jpg",
                "name": "George",
                "steam64": "76561198880367503"
            },
            "downvotes": 0,
            "epilepsy": false,
            "height": 430,
            "humor": false,
            "id": 272605,
            "language": "en",
            "lock": true,
            "mime": "image/png",
            "notes": null,
            "nsfw": false,
            "score": 0,
            "style": "alternate",
            "thumb": "https://cdn2.steamgriddb.com/file/sgdb-cdn/thumb/cce3daec802095758634087529d8eecd.jpg?",
            "upvotes": 0,
            "url": "https://cdn2.steamgriddb.com/file/sgdb-cdn/grid/cce3daec802095758634087529d8eecd.png?",
            "width": 920
        },
```

So I was about to submit the following change as PR, but then noticed you're working on a cleaned up version, so I just wanted to leave this here. 

```diff
diff --git a/example/main.cpp b/example/main.cpp
index 32f3687..cfeacfc 100644
--- a/example/main.cpp
+++ b/example/main.cpp
@@ -351,6 +351,10 @@ void frame_showOnlineTitleIcons(std::string gameId){
         for (auto it : iconList["data"])
         {
             brls::Logger::info(it["id"].dump());
+            if (it["lock"].get<bool>()) {
+                brls::Logger::info("skipped DMCA hidden image");
+                continue;
+            }
             brls::ListItem* litem = new brls::ListItem(it["id"].dump());
             litem->getFocusEvent()->subscribe([=](brls::View* view) {
             rootFrame->getSidebar()->getButton()->getClickEvent()->unsubscribeAll();
```

**Comment by Slluxx** [comment]
Sounds good, thank you for the heads up!
Im currently moving into a new apartment and kinda busy with some reallife things but the new version should come soon ™️ 

Im going to leave this open so it reminds me whenever i have everything set up at my new place

**Comment by mtnair** [comment]
I ran into the same problem, fixed it myself for now.
I also experienced a crash when all images are hidden, so I added an extra check if the list has any items and added a "No icon found" item if not.

I also had to comment out line 45 in `swkbd.cpp` (`swkbdConfigSetStringLenMaxExt(&config, 1);`), which prevented the homebrew from compiling at all. Looks like this function has been removed.

**Comment by Slluxx** [comment]
fixed, thank you very much @Schaefers
